language: c

sudo: false

addons:
  apt:
    sources:
    - hvr-ghc
    packages:
    - ghc-8.2.2

before_install:
 - mkdir -p ~/.local/bin
 - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
 - export PATH=~/.local/bin:/opt/ghc/$GHCVER/bin:$PATH
 - chmod a+x ~/.local/bin/stack

install:
  - stack --no-terminal --skip-ghc-check setup

script:
  - stack --no-terminal --skip-ghc-check build
  - stack --no-terminal --skip-ghc-check build --test --test-arguments '-p "$0 !~ /Loops WITH space leaks/ " --num-threads=2 +RTS -qa -qm -N2 -maxN2 -RTS'
  - stack --no-terminal --skip-ghc-check haddock

cache:
  directories:
  - ~/.stack
  - ~/.local
  - ~/.stack-work-cache
  apt: true
